### ISSUE TITLE
Enhance Footer Section

### ISSUE THREAD

**Issue by Harithaa2004** [rajputpritesh1/GSAP-Animated-Landing-Page#1]
Description: The current footer includes basic copyright information, but it could be enhanced to improve user experience. Suggested improvements:

Add social media links.

Include a site map for better navigation.

Ensure the footer is fully responsive on all devices.

kindly assign this to me

**Comment by rajputpritesh1** [comment]
> Description: The current footer includes basic copyright information, but it could be enhanced to improve user experience. Suggested improvements:
> 
> Add social media links.
> 
> Include a site map for better navigation.
> 
> Ensure the footer is fully responsive on all devices.
> 
> kindly assign this to me

You are allowed, Thank You!

**Comment by Harithaa2004** [comment]
Hi @rajputpritesh1,

I noticed that the GSAP-Animated-Landing-Page repository isn’t currently tagged for Hacktoberfest. Would it be possible to add the "hacktoberfest" topic to the repository and label the issues with "hacktoberfest-accepted"? This would allow contributors like me to earn credit for our contributions during the event.

**Comment by rajputpritesh1** [comment]
It's already labeled please check

**Comment by Harithaa2004** [comment]
in the labels, hactoberfest accepted must be put
![Screenshot 2024-10-16 122448](https://github.com/user-attachments/assets/98e3348c-5efc-4a10-a85f-505d7cd8bef7)

like this

**Comment by rajputpritesh1** [comment]
Done
